# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: Henry Yang
google_analytics: Henry Yang
title: Henry Yang

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Henry Yang's Personal Page

description: Stylish Jekyll Theme
author:
  name: Henry Yang
  email: yanghanyugg@gmail.com
  github: henryyang1993
  twitter: henryyangtt
  linkedin: hanyuy
  weibo: henryyangmicroblog
  bio: Learn and Be Curious!
  email_md5: 1f6be677c6135b37f5080532f3b20008

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

gems:
  - jekyll-paginate