# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: Henry Yang
google_analytics: Henry Yang
title: Henry Yang

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Henry Yang

description: Stylish Jekyll Theme
author:
  name: Henry Yang
  email: yanghanyugg@gmail.com
  github: henryyang1993
  twitter: yanghanyutwitte
  linkedin: hanyuy
  bio: Spend your money on the things money can buy. Spend your time on the things money can't buy. - Haruki Murakami

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate